language: csharp
mono: none
dotnet: 5.0.101

script:
  - dotnet restore EFCore.BulkExtensions.sln
  - dotnet build EFCore.BulkExtensions.sln
  - dotnet pack EFCore.BulkExtensions.sln -c Release -o packages

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh $NUGET_KEY
  on:
    branch: LKG
    tags: true
