version: 3.1.{build}
configuration: Release
services:
- postgresql12
- mysql

before_build:
- cmd: nuget restore EFCore.BulkExtensions.sln

build:
  project: EFCore.BulkExtensions.sln
  publish_nuget: false
  publish_nuget_symbols: false
  verbosity: minimal
